name: Push to Docker Hub

on:
  push:
    branches:
      - main
jobs:
  build:
    name: build binary
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: |
          go build -o bussiness-card main.go

      - name: login docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: build and push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bussiness-card .
          docker push ${{ secrets.DOCKER_USERNAME }}/bussiness-card